version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - ./PHP:/var/www/html
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./BD:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    env_file:
      - .env
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
